# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

  - repo: local
    hooks:
      - id: poetry-export
        name: Poetry exports requirements
        entry: poetry export --output=requirements.txt
        pass_filenames: false
        language: system
      - id: pytest-check
        name: pytest-check
        entry: poetry run pytest test.py
        language: system
        pass_filenames: false
        always_run: true
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.0
    hooks:
    -   id: absolufy-imports

  - repo: https://github.com/hadialqattan/pycln
    rev: v1.0.3
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
    -   id: pyupgrade
        args: [--py39-plus]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
