version: 2

seeds:
  - name: imoveis_AC
    description: "Real estate data for Acre (AC)"
    columns:
      - name: link
        description: "Unique identifier for the property listing"
        tests:
          - not_null
          - unique
      - name: preco
        tests:
          - not_null
      - name: avaliacao
        tests:
          - not_null
      - name: cidade
        tests:
          - not_null
      - name: estado
        tests:
          - not_null
          - accepted_values:
              values: ["AC"]

  - name: imoveis_AL
    description: "Real estate data for Alagoas (AL)"
    columns:
      - name: link
        description: "Unique identifier for the property listing"
        tests:
          - not_null
          - unique
      - name: preco
        tests:
          - not_null
      - name: avaliacao
        tests:
          - not_null
      - name: cidade
        tests:
          - not_null
      - name: estado
        tests:
          - not_null
          - accepted_values:
              values: ["AL"]

  - name: imoveis_AM
    description: "Real estate data for Amazonas (AM)"
    columns:
      - name: link
        description: "Unique identifier for the property listing"
        tests:
          - not_null
          - unique
      - name: preco
        tests:
          - not_null
      - name: avaliacao
        tests:
          - not_null
      - name: cidade
        tests:
          - not_null
      - name: estado
        tests:
          - not_null
          - accepted_values:
              values: ["AM"]

  - name: imoveis_AP
    description: "Real estate data for Amapá (AP)"
    columns:
      - name: link
        description: "Unique identifier for the property listing"
        tests:
          - not_null
          - unique
      - name: preco
        tests:
          - not_null
      - name: avaliacao
        tests:
          - not_null
      - name: cidade
        tests:
          - not_null
      - name: estado
        tests:
          - not_null
          - accepted_values:
              values: ["AP"]

  - name: imoveis_BA
    description: "Real estate data for Bahia (BA)"
    columns:
      - name: link
        description: "Unique identifier for the property listing"
        tests:
          - not_null
          - unique
      - name: preco
        tests:
          - not_null
      - name: avaliacao
        tests:
          - not_null
      - name: cidade
        tests:
          - not_null
      - name: estado
        tests:
          - not_null
          - accepted_values:
              values: ["BA"]

  - name: imoveis_CE
    description: "Real estate data for Ceará (CE)"
    columns:
      - name: link
        description: "Unique identifier for the property listing"
        tests:
          - not_null
          - unique
      - name: preco
        tests:
          - not_null
      - name: avaliacao
        tests:
          - not_null
      - name: cidade
        tests:
          - not_null
      - name: estado
        tests:
          - not_null
          - accepted_values:
              values: ["CE"]

  - name: imoveis_DF
    description: "Real estate data for Distrito Federal (DF)"
    columns:
      - name: link
        description: "Unique identifier for the property listing"
        tests:
          - not_null
          - unique
      - name: preco
        tests:
          - not_null
      - name: avaliacao
        tests:
          - not_null
      - name: cidade
        tests:
          - not_null
      - name: estado
        tests:
          - not_null
          - accepted_values:
              values: ["DF"]

  - name: imoveis_ES
    description: "Real estate data for Espírito Santo (ES)"
    columns:
      - name: link
        description: "Unique identifier for the property listing"
        tests:
          - not_null
          - unique
      - name: preco
        tests:
          - not_null
      - name: avaliacao
        tests:
          - not_null
      - name: cidade
        tests:
          - not_null
      - name: estado
        tests:
          - not_null
          - accepted_values:
              values: ["ES"]

  - name: imoveis_GO
    description: "Real estate data for Goiás (GO)"
    columns:
      - name: link
        description: "Unique identifier for the property listing"
        tests:
          - not_null
          - unique
      - name: preco
        tests:
          - not_null
      - name: avaliacao
        tests:
          - not_null
      - name: cidade
        tests:
          - not_null
      - name: estado
        tests:
          - not_null
          - accepted_values:
              values: ["GO"]

  - name: imoveis_MA
    description: "Real estate data for Maranhão (MA)"
    columns:
      - name: link
        description: "Unique identifier for the property listing"
        tests:
          - not_null
          - unique
      - name: preco
        tests:
          - not_null
      - name: avaliacao
        tests:
          - not_null
      - name: cidade
        tests:
          - not_null
      - name: estado
        tests:
          - not_null
          - accepted_values:
              values: ["MA"]

  - name: imoveis_MG
    description: "Real estate data for Minas Gerais (MG)"
    columns:
      - name: link
        description: "Unique identifier for the property listing"
        tests:
          - not_null
          - unique
      - name: preco
        tests:
          - not_null
      - name: avaliacao
        tests:
          - not_null
      - name: cidade
        tests:
          - not_null
      - name: estado
        tests:
          - not_null
          - accepted_values:
              values: ["MG"]

  - name: imoveis_MS
    description: "Real estate data for Mato Grosso do Sul (MS)"
    columns:
      - name: link
        description: "Unique identifier for the property listing"
        tests:
          - not_null
          - unique
      - name: preco
        tests:
          - not_null
      - name: avaliacao
        tests:
          - not_null
      - name: cidade
        tests:
          - not_null
      - name: estado
        tests:
          - not_null
          - accepted_values:
              values: ["MS"]

  - name: imoveis_MT
    description: "Real estate data for Mato Grosso (MT)"
    columns:
      - name: link
        description: "Unique identifier for the property listing"
        tests:
          - not_null
          - unique
      - name: preco
        tests:
          - not_null
      - name: avaliacao
        tests:
          - not_null
      - name: cidade
        tests:
          - not_null
      - name: estado
        tests:
          - not_null
          - accepted_values:
              values: ["MT"]

  - name: imoveis_PA
    description: "Real estate data for Pará (PA)"
    columns:
      - name: link
        description: "Unique identifier for the property listing"
        tests:
          - not_null
          - unique
      - name: preco
        tests:
          - not_null
      - name: avaliacao
        tests:
          - not_null
      - name: cidade
        tests:
          - not_null
      - name: estado
        tests:
          - not_null
          - accepted_values:
              values: ["PA"]

  - name: imoveis_PB
    description: "Real estate data for Paraíba (PB)"
    columns:
      - name: link
        description: "Unique identifier for the property listing"
        tests:
          - not_null
          - unique
      - name: preco
        tests:
          - not_null
      - name: avaliacao
        tests:
          - not_null
      - name: cidade
        tests:
          - not_null
      - name: estado
        tests:
          - not_null
          - accepted_values:
              values: ["PB"]

  - name: imoveis_PE
    description: "Real estate data for Pernambuco (PE)"
    columns:
      - name: link
        description: "Unique identifier for the property listing"
        tests:
          - not_null
          - unique
      - name: preco
        tests:
          - not_null
      - name: avaliacao
        tests:
          - not_null
      - name: cidade
        tests:
          - not_null
      - name: estado
        tests:
          - not_null
          - accepted_values:
              values: ["PE"]

  - name: imoveis_PI
    description: "Real estate data for Piauí (PI)"
    columns:
      - name: link
        description: "Unique identifier for the property listing"
        tests:
          - not_null
          - unique
      - name: preco
        tests:
          - not_null
      - name: avaliacao
        tests:
          - not_null
      - name: cidade
        tests:
          - not_null
      - name: estado
        tests:
          - not_null
          - accepted_values:
              values: ["PI"]

  - name: imoveis_PR
    description: "Real estate data for Paraná (PR)"
    columns:
      - name: link
        description: "Unique identifier for the property listing"
        tests:
          - not_null
          - unique
      - name: preco
        tests:
          - not_null
      - name: avaliacao
        tests:
          - not_null
      - name: cidade
        tests:
          - not_null
      - name: estado
        tests:
          - not_null
          - accepted_values:
              values: ["PR"]

  - name: imoveis_RJ
    description: "Real estate data for Rio de Janeiro (RJ)"
    columns:
      - name: link
        description: "Unique identifier for the property listing"
        tests:
          - not_null
          - unique
      - name: preco
        tests:
          - not_null
      - name: avaliacao
        tests:
          - not_null
      - name: cidade
        tests:
          - not_null
      - name: estado
        tests:
          - not_null
          - accepted_values:
              values: ["RJ"]

  - name: imoveis_RN
    description: "Real estate data for Rio Grande do Norte (RN)"
    columns:
      - name: link
        description: "Unique identifier for the property listing"
        tests:
          - not_null
          - unique
      - name: preco
        tests:
          - not_null
      - name: avaliacao
        tests:
          - not_null
      - name: cidade
        tests:
          - not_null
      - name: estado
        tests:
          - not_null
          - accepted_values:
              values: ["RN"]

  - name: imoveis_RO
    description: "Real estate data for Rondônia (RO)"
    columns:
      - name: link
        description: "Unique identifier for the property listing"
        tests:
          - not_null
          - unique
      - name: preco
        tests:
          - not_null
      - name: avaliacao
        tests:
          - not_null
      - name: cidade
        tests:
          - not_null
      - name: estado
        tests:
          - not_null
          - accepted_values:
              values: ["RO"]

  - name: imoveis_RR
    description: "Real estate data for Roraima (RR)"
    columns:
      - name: link
        description: "Unique identifier for the property listing"
        tests:
          - not_null
          - unique
      - name: preco
        tests:
          - not_null
      - name: avaliacao
        tests:
          - not_null
      - name: cidade
        tests:
          - not_null
      - name: estado
        tests:
          - not_null
          - accepted_values:
              values: ["RR"]

  - name: imoveis_RS
    description: "Real estate data for Rio Grande do Sul (RS)"
    columns:
      - name: link
        description: "Unique identifier for the property listing"
        tests:
          - not_null
          - unique
      - name: preco
        tests:
          - not_null
      - name: avaliacao
        tests:
          - not_null
      - name: cidade
        tests:
          - not_null
      - name: estado
        tests:
          - not_null
          - accepted_values:
              values: ["RS"]

  - name: imoveis_SC
    description: "Real estate data for Santa Catarina (SC)"
    columns:
      - name: link
        description: "Unique identifier for the property listing"
        tests:
          - not_null
          - unique
      - name: preco
        tests:
          - not_null
      - name: avaliacao
        tests:
          - not_null
      - name: cidade
        tests:
          - not_null
      - name: estado
        tests:
          - not_null
          - accepted_values:
              values: ["SC"]

  - name: imoveis_SE
    description: "Real estate data for Sergipe (SE)"
    columns:
      - name: link
        description: "Unique identifier for the property listing"
        tests:
          - not_null
          - unique
      - name: preco
        tests:
          - not_null
      - name: avaliacao
        tests:
          - not_null
      - name: cidade
        tests:
          - not_null
      - name: estado
        tests:
          - not_null
          - accepted_values:
              values: ["SE"]

  - name: imoveis_SP
    description: "Real estate data for São Paulo (SP)"
    columns:
      - name: link
        description: "Unique identifier for the property listing"
        tests:
          - not_null
          - unique
      - name: preco
        tests:
          - not_null
      - name: avaliacao
        tests:
          - not_null
      - name: cidade
        tests:
          - not_null
      - name: estado
        tests:
          - not_null
          - accepted_values:
              values: ["SP"]

  - name: imoveis_TO
    description: "Real estate data for Tocantins (TO)"
    columns:
      - name: link
        description: "Unique identifier for the property listing"
        tests:
          - not_null
          - unique
      - name: preco
        tests:
          - not_null
      - name: avaliacao
        tests:
          - not_null
      - name: cidade
        tests:
          - not_null
      - name: estado
        tests:
          - not_null
          - accepted_values:
              values: ["TO"]
