name: Run every day
on: 
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
    
  

  
jobs:
  build:
    name: ETL and pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: x64
      - name: Install pipenv
        run: pip3 install pipenv
      - name: Install dependencies
        run: pipenv install --python /usr/bin/python3
      - name: Extract data
        run: pipenv run python etl.py
      - name: Compile data
        run: pipenv run python update.py
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}        
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash

