name: Run every day
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
        
  
jobs:
  build:
    name: ETL and pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: x64
      - name: Install pipenv
        run: pip3 install pipenv
      - name: Install dependencies
        run: pipenv install
      - name: Extract data
        run: pipenv run python etl.py
      - name: Compile data
        run: pipenv run python update.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
